---
title: "PP-nofish-immob"
output: html_document
date: '2022-03-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r source_setup, message = FALSE}
source("05_Various/setup.R")

model_runs <- readr::read_rds("~/Desktop/model_runs.rds")

df_experiment <- expand.grid(amplitude_mod = c(0.05, 0.5, 1.0), 
                             fishpop = c(1, 2)) %>%
  dplyr::mutate(move = dplyr::case_when(fishpop == 1 ~ "rand", 
                                        fishpop == 2 ~ "behav"))
```

This is the repiort and shiws

```{r ttl_prod}
purrr::map_dfr(seq_along(model_runs), function(i) {
  
  dplyr::filter(model_runs[[i]]$seafloor, timestep == max_i, reef == 0) %>%
    dplyr::summarise(dplyr::across(c(ag_biomass, bg_biomass, ag_production, bg_production),
                                   function(x) c(mean = mean(x), sum = sum(x)))) %>%
    tibble::add_column(fun = c("mean", "sum"), .before = "ag_biomass") %>%
    tidyr::pivot_longer(-fun) %>% 
    dplyr::mutate(amplitude = df_experiment[i, 1], 
                  fishpop = ifelse(test = df_experiment[i, 2] == 1, yes = "nofish", no = "immob"))}) %>%
  tidyr::pivot_wider(names_from = fishpop, values_from = value) %>% 
  dplyr::mutate(value.diff = ((immob - nofish) / immob) * 100) %>% 
  dplyr::arrange(desc(fun), name, amplitude) %>% 
  DT::datatable(caption = "Random movement: Mean production per sqm/day", 
                options = list(pageLength = 12), filter = "top")
```

```{r prod_gg, fig.align="center", out.width="100%"}
purrr::map_dfr(seq_along(model_runs), function(i) { 
  arrR::get_production(model_runs[[i]]) %>% 
  dplyr::mutate(amplitude = df_experiment[i, 1], 
                fishpop = ifelse(test = df_experiment[i, 2] == 1, 
                                 yes = "nofish", no = "immob"))
  }) %>%
  tidyr::pivot_longer(-c(timestep, amplitude, fishpop), names_to = "part") %>% 
  ggplot() + 
  geom_line(aes(x = timestep, y = value, col = fishpop)) + 
  facet_wrap(. ~ part * amplitude, scales = "free_y") + 
  labs(x = "Timesteps", y = expression(paste(Delta, "PP (ttl environ)"))) +
  theme_classic() +
  theme(legend.position = "bottom")
```

```
print("5")
```
